apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: foodgram
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:17
        command:
        - sh
        - -c
        - |
          until pg_isready -h postgres-service -p 5432 -U $(DB_USER) -d $(DB_NAME); do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
        env:
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_NAME
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: foodgram-secret
              key: DB_PASSWORD
      containers:
      - name: django
        image: santino9/foodgram-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_ENGINE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_ENGINE
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_PORT
        - name: DJANGO_DEBUG
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DJANGO_DEBUG
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DJANGO_ALLOWED_HOSTS
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: foodgram-secret
              key: DB_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: foodgram-secret
              key: SECRET_KEY
        volumeMounts:
        - name: static-volume
          mountPath: /app/static
        - name: media-volume
          mountPath: /app/media
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 8000
#          initialDelaySeconds: 30
#          periodSeconds: 10
#        readinessProbe:
#            httpGet:
#              path: /
#              port: 8000
#            initialDelaySeconds: 5
#            periodSeconds: 5
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-volume-pvc
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-volume-pvc
