apiVersion: batch/v1
kind: Job
metadata:
  name: frontend-build
  namespace: foodgram
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: frontend-builder
        image: santino9/foodgram-frontend:latest
        command:
        - sh
        - -c
        - |
          npm install && npm run build
          cp -r /app/build/* /frontend-static/
        volumeMounts:
        - name: frontend-static
          mountPath: /frontend-static
      volumes:
      - name: frontend-static
        persistentVolumeClaim:
          claimName: frontend-static-pvc
