apiVersion: v1
kind: Secret
metadata:
  name: foodgram-secret
  namespace: foodgram
type: Opaque
data:
  DB_PASSWORD: Q29yZURjb2xvcjYw
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXEqKTd0bmFyZSgwI2RfPTBkd2hlMTNAKiMoQGslb3lmbHlpaDl4d3o2MXZoKTUpX2Zt
