postgresql:
  database:
    password: ref+vault://secret/foodgram/postgres?proto=https#/password

secret:
  DB_PASSWORD: ref+vault://secret/foodgram/backend?proto=https#/DB_PASSWORD
  SECRET_KEY: ref+vault://secret/foodgram/backend?proto=https#/SECRET_KEY

nyt:
  apiKey: ref+vault://secret/foodgram/nyt?proto=https#/api_key

rabbitmq:
  username: ref+vault://secret/rabbitmq?proto=https#/username
  password: ref+vault://secret/rabbitmq?proto=https#/password

redis:
  auth:
    password: ref+vault://secret/redis?proto=https#/password
