server:
  # Используем один под (dev mode не для production)
  affinity: ""
  ha:
    enabled: false
  # Для теста можно использовать standalone режим
  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/vault/data"
      }
  # Включить веб-интерфейс
  ui:
    enabled: true
    serviceType: "ClusterIP" # Мы позже сделаем Ingress

  # Для теста отключаем tls (в production обязательно включить)
  global:
    tlsDisable: true