version: '3.8'

services:
  db:
    image: postgres:13
    container_name: foodgram-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: foodgram-backend
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SECRET_KEY: ${DJANGO_SECRET_KEY}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: foodgram-frontend
    volumes:
      - frontend_static:/app/result_build

  nginx:
    image: nginx:1.25.4-alpine
    container_name: foodgram-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_static:/usr/share/nginx/html:ro
      - static_volume:/usr/share/nginx/html/static:ro
      - media_volume:/usr/share/nginx/html/media:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  frontend_static:
  static_volume:
  media_volume:
