apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foodgram.fullname" . }}-backend-config
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.backend.configMap.data | nindent 2 }}
