apiVersion: v1
kind: Service
metadata:
  name: {{ include "foodgram.fullname" . }}-backend
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "foodgram.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort | default .Values.backend.service.port }}
