apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foodgram.fullname" . }}-config
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
data:
  # Django settings
  DB_ENGINE: {{ .Values.backend.configMap.data.DB_ENGINE | quote }}
  DB_NAME: {{ .Values.backend.configMap.data.DB_NAME | quote }}
  DB_USER: {{ .Values.backend.configMap.data.DB_USER | quote }}
  DB_HOST: {{ .Values.backend.configMap.data.DB_HOST | quote }}
  DB_PORT: {{ .Values.backend.configMap.data.DB_PORT | quote }}
  DJANGO_DEBUG: {{ .Values.backend.configMap.data.DJANGO_DEBUG | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.backend.configMap.data.DJANGO_ALLOWED_HOSTS | quote }}

  # RabbitMQ / Celery Broker settings
  RABBITMQ_HOST: {{ .Values.rabbitmq.host | default "my-rabbitmq.default.svc.cluster.local" | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | default "5672" | quote }}

  # Celery settings
  CELERY_BROKER_URL: {{ .Values.celery.brokerUrl | default (printf "redis://:%s@%s:%s/0" .Values.redis.password .Values.redis.host .Values.redis.port) | quote }}
  CELERY_RESULT_BACKEND: {{ .Values.celery.resultBackend | default (printf "redis://:%s@%s:%s/0" .Values.redis.password .Values.redis.host .Values.redis.port) | quote }}
  CELERY_ACCEPT_CONTENT: {{ .Values.celery.acceptContent | default "json" | quote }}
  CELERY_TASK_SERIALIZER: {{ .Values.celery.taskSerializer | default "json" | quote }}
  CELERY_RESULT_SERIALIZER: {{ .Values.celery.resultSerializer | default "json" | quote }}
  CELERY_TIMEZONE: {{ .Values.celery.timezone | default "UTC" | quote }}

  # Flower settings
  FLOWER_PORT: {{ .Values.flower.service.port | default "5555" | quote }}

  # Redis settings
  REDIS_HOST: {{ .Release.Name }}-redis
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""

  # Django cache
  CACHE_URL: "redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)/1"
