apiVersion: v1
kind: Service
metadata:
  name: {{ include "foodgram.fullname" . }}-nginx
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    {{- include "foodgram.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.service.port }}
      targetPort: 80
