{{- if .Values.workers.foodish.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "foodgram.fullname" . }}-foodish-output
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
    app.kubernetes.io/component: foodish-worker
spec:
  accessModes:
    - {{ .Values.workers.foodish.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.workers.foodish.persistence.size }}
  {{- if .Values.workers.foodish.persistence.storageClass }}
  storageClassName: {{ .Values.workers.foodish.persistence.storageClass }}
  {{- end }}
{{- end }}
---
{{- if .Values.workers.nyt.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "foodgram.fullname" . }}-nyt-output
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
    app.kubernetes.io/component: nyt-worker
spec:
  accessModes:
    - {{ .Values.workers.nyt.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.workers.nyt.persistence.size }}
  {{- if .Values.workers.nyt.persistence.storageClass }}
  storageClassName: {{ .Values.workers.nyt.persistence.storageClass }}
  {{- end }}
{{- end }}
