apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foodgram.fullname" . }}-secret
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | required "secret.DB_PASSWORD is required" | b64enc | quote }}
  SECRET_KEY: {{ .Values.secret.SECRET_KEY | required "secret.SECRET_KEY is required" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.secretName | default "rabbitmq-secrets" }}
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.rabbitmq.userKey | default "username" }}: {{ .Values.rabbitmq.username | required "rabbitmq.username is required" | b64enc | quote }}
  {{ .Values.rabbitmq.passwordKey | default "password" }}: {{ .Values.rabbitmq.password | required "rabbitmq.password is required" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nyt.secretName | default "nyt-secret" }}
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.nyt.apiKeyKey | default "NYT_API_KEY" }}: {{ .Values.nyt.apiKey | required "nyt.apiKey is required" | b64enc | quote }}
