apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: {{ include "foodgram.namespace" . }}
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.address }}
      path: "foodgram"      # KV mount name (vault secrets enable -path=foodgram kv-v2)
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.vault.role }}
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
