apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foodgram.fullname" . }}-secret
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | required "secret.DB_PASSWORD is required" | b64enc | quote }}
  SECRET_KEY: {{ .Values.secret.SECRET_KEY | required "secret.SECRET_KEY is required" | b64enc | quote }}
