# Default values for foodgram-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Основные параметры приложения
backend:
  configMap:
    data:
      DB_ENGINE: "django.db.backends.postgresql"
      DB_NAME: "foodgram"
      DB_USER: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: "*"
  replicaCount: 2
  image:
    repository: santino9/foodgram-backend
    tag: latest
    pullPolicy: Always
  service:
    port: 8000
    type: ClusterIP
  livenessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Секреты
secret:
  DB_PASSWORD: ""
  SECRET_KEY: ""

# Параметры nginx
nginx:
  replicaCount: 1
  image:
    repository: nginx
    tag: "1.25.4-alpine"
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
  livenessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Постоянные тома
persistence:
  static:
    enabled: true
    size: 2Gi
    accessMode: ReadWriteOnce
    storageClass: "standard"
    existingClaim: ""
  media:
    enabled: true
    size: 2Gi
    accessMode: ReadWriteOnce
    storageClass: "standard"
    existingClaim: ""
  frontendStatic:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: "standard"
    existingClaim: ""

# Job для сборки фронтенда
frontendJob:
  enabled: true
  image:
    repository: santino9/foodgram-frontend
    tag: latest
  command: |
    npm install && npm run build
    cp -r /app/build/* /frontend-static/

# Ingress
ingress:
  enabled: true
  ingressClassName: nginx
  annotations: {}
  tls:
    - hosts:
        - foodgram.local
      secretName: foodgram-tls
  hosts:
    - host: foodgram.local
      paths:
        - path: /
          pathType: Prefix

# Подчарт PostgreSQL
postgresql:
  enabled: true
  database:
    name: foodgram
    user: postgres
    password: ""
  persistence:
    size: 2Gi
    storageClass: "manual"
  image:
    repository: postgres
    tag: "17"

httpRoute:
  enabled: false

rabbitmq:
  username: ""
  password: ""
  host: "my-rabbitmq.default.svc.cluster.local"
  vhost: "foodgram"
  port: 5672
  secretName: rabbitmq-secrets
  userKey: username
  passwordKey: password

celery:
  resultBackend: "rpc://"
  acceptContent: "json"
  taskSerializer: "json"
  resultSerializer: "json"
  timezone: "UTC"

  worker:
    enabled: true
    replicaCount: 2
    command:
      - celery
      - -A
      - foodgram
      - worker
      - -l
      - info
      - -Q
      - foodish,nyt
    persistence:
      enabled: true
      size: 1Gi
      storageClass: "standard"
      outputDir: "/output"
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Flower настройки
flower:
  enabled: true
  replicaCount: 1
  image:
    repository: mher/flower
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5555
    annotations: {}
  prometheus:
    enabled: true
  extraArgs: []
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  ingress:
    enabled: true
    ingressClassName: nginx
    host: flower.local
    path: /
    annotations: {}
    tls: []

nyt:
  api_key: ""
  secretName: nyt-secret
  apiKeyKey: NYT_API_KEY
