apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ include "foodgram.namespace" . }}
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "foodgram.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: gunicorn
      port: 8000
      targetPort: gunicorn
      protocol: TCP
