apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: foodgram-external-secret
  namespace: {{ include "foodgram.namespace" . }}
  labels:
    {{- include "foodgram.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: {{ include "foodgram.secretName" . }}
    creationPolicy: Owner
  data:
    # Django
    - secretKey: SECRET_KEY
      remoteRef:
        key: app
        property: SECRET_KEY

    - secretKey: DB_NAME
      remoteRef:
        key: app
        property: DB_NAME

    - secretKey: DB_USER
      remoteRef:
        key: app
        property: DB_USER

    - secretKey: DB_PASSWORD
      remoteRef:
        key: app
        property: DB_PASSWORD
