# Generated by Django 5.2.3 on 2025-06-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('gram', 'грамм'), ('kilogram', 'килограмм'), ('milliliter', 'миллилитр'), ('liter', 'литр'), ('piece', 'штука')], default='gram', max_length=100, verbose_name='Единица измерения'),
        ),
    ]
