# Generated by Django 5.2.3 on 2025-06-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_measurement_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement_value',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=100, verbose_name='Единица измерения'),
        ),
    ]
